data:
  bond_name:
  - CH
  - OH
  - O
  file:
  - IONS+CENTERS+cell_sorted_merge.xyz
  itp_file: methanol.mol
  type: xyz
learning_rate:
  type: fix
loss:
  type: mse
model:
  M: 20
  Mb: 6
  modelname:
  - ch
  - oh
  - o
  nfeature: 288
training:
  batch_size: 32
  device: cpu
  learning_rate:
    gamma: 0.95
    start_lr: 1e-2
    type: ExponentialLR
  max_epochs: 5
  modeldir:
  - model_ch
  - model_oh
  - model_o
  n_train: 900
  n_val: 100
  restart: false
  validation_batch_size: 32
