model:
  modelname: coh    # specify name
  nfeature:  288   # length of descriptor
  M:         20    # M  (embedding matrix size)
  Mb:        6     # Mb (embedding matrix size, smaller than M)

learning_rate:
  type: fix

loss:
  type: mse        # mean square error

data:
  type: xyz        # or xyz
  file:
    - "traj/test.xyz"
  itp_file: pg2asym.mol
  bond_name: COH

training:
  device:     cpu # Torchのdevice
  batch_size: 32  # batch size for training
  validation_batch_size: 32 # batch size for validation
  max_epochs: 10
  learning_rate:
    type: MultiStepLR
    start_lr: 1e-2 # starting learning rate
    milestones: [50,100]
    gamma: 0.1
  n_train:      900     # the number of training data (frame)
  n_val:        100     # the number of validation data (frame)
  modeldir:  model_coh   # directory to save models
  restart:   False       # If restart training
