model:
  modelname: cc    # specify name
  nfeature:  288   # length of descriptor
  M:         20    # M  (embedding matrix size)
  Mb:        6     # Mb (embedding matrix size, smaller than M)

learning_rate:
  type: fix

loss:
  type: mse        # mean square error

data:
  type: xyz        # or xyz
  file:
    - "traj/IONS+CENTERS+cell_sorted_merge.xyz"
  itp_file: pg2asym.mol
  bond_name: CC

training:
  device:     cpu # Torchのdevice
  batch_size: 32  # batch size for training
  validation_batch_size: 32 # batch size for validation
  max_epochs: 40
  learning_rate: 1e-2 # starting learning rate
  n_train:       9000    # the number of training data (frame)
  n_val:         1000    # the number of validation data (frame)
  modeldir:  model_cc # directory to save models
  restart:   False    # If restart training
