general:
  itpfilename: methanol.mol
  bondfilename: PG_bondlist.txt
  savedir: dipole_50ps/
  temperature: 298
  timestep: 10
descriptor:
  calc: 1
  directory: ./
  xyzfilename: traj_1.xyz
  savedir: dipole_50ps/
  descmode: 2
  desctype: allinone
  haswannier: 1
  interval: 1
  desc_coh: 0
predict:
  calc: 1
  desc_dir: dipole_50ns/
  model_dir: /home/k0151/k015124/c++/20230721_PG500K_model_rotate/ #/work/k0151/k015124/predict_dipole/202306014_model_rotate_PG/
  modelmode: rotate
  bondspecies: 4
  save_truey: 0
  
