

model:
  modelname: test
  nfeature:  288
  M:         20
  Mb:        6

learning_rate:
  test: test

loss:
  test: test


data:
  type: descriptor # or xyz
  file:
   - "descs_bulk/cc" 

  
training:
  device:     cpu # Torchのdevice
  batch_size: 32  # 訓練のバッチサイズ
  validation_batch_size: 32 # validationのバッチサイズ
  max_epochs: 40
  learning_rate: 1e-2 # starting learning rate
  n_train: 2100000    # データ数（xyzのフレーム数ではないので注意．純粋なデータ数）
  n_val:     10000
  modeldir:  model_test
  restart:   False
  
  
