#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Module providing functionality to plot histograms of molecular/bond dipoles.

This module is part of the cpextract_diel subcommand, designed for processing
dipole.txt files generated by dieltools. It includes the Plot_histgram class
which handles the data loading, histogram generation, and plotting.

CPextract.py diel subcommand for processing dipole.txt files generated by dieltools

- histgram :: Plot histgram of molecule dipole/bond dipole
"""

import argparse

import pandas as pd

from mlwc.fourier.moldipole.moldipole import moldipole
from mlwc.fourier.moldipole.moldipole_io import read_file
from mlwc.include.mlwc_logger import setup_library_logger

logger = setup_library_logger("MLWC." + __name__)


def command_diel_histgram(args: argparse.Namespace) -> int:
    """Entry point of CPextract.py diel hist"""
    logger.info(" cpextract.py diel hist")
    moldipole_instance: moldipole = read_file(args.Filename)
    moldipole_instance.print_info()
    df: pd.DataFrame = moldipole_instance.get_dipole_histgram()
    df.to_csv(args.Filename + "_dipole_histgram.csv")
    moldipole_instance.plot_dipole_histgram()
    return 0
