#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Module providing functionality to plot histograms of molecular/bond dipoles.

This module is part of the cpextract_diel subcommand, designed for processing
dipole.txt files generated by dieltools. It includes the Plot_histgram class
which handles the data loading, histogram generation, and plotting.

CPextract.py diel subcommand for processing dipole.txt files generated by dieltools

- histgram :: Plot histgram of molecule dipole/bond dipole
"""
# TODO :: get_histgramとplot_histgramの実装はmoldipoleに移行する

import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from mlwc.include.mlwc_logger import setup_library_logger

logger = setup_library_logger("MLWC." + __name__)


class PlotDipoleHistgram:
    """
    Plots a histogram of molecular or bond dipoles.

    This class takes a dipole data file as input, calculates the magnitude of
    the dipole moments, and generates a histogram. It provides methods to
    save the histogram data to a file and plot the histogram.


    Returns:
        _type_: _description_
    """

    def __init__(self, dipole_filename: str, max_dipole: float = None):
        """
        Initializes the Plot_histgram class.

        Parameters
        ----------
        dipole_filename : str
            Path to the dipole data file.
        max : float, optional
            Maximum value for the histogram. If None, it is determined from the data.
            The default is None.

        Raises
        ------
        FileNotFoundError
            If the specified dipole file does not exist.

        Examples
        --------
        >>> hist_plotter = Plot_histgram("dipole.txt", max=5.0)
        >>> print(hist_plotter._filename)
        dipole.txt
        """
        self._filename = dipole_filename

        if not os.path.isfile(self._filename):
            raise FileNotFoundError(
                f" ERROR :: {str(self._filename)} does not exist !!"
            )
        self.data = np.loadtxt(self._filename)  # load txt in numpy ndarray
        self.max = max_dipole
        logger.info(" --------- ")
        logger.info(f" number of data :: {np.shape(self.data)}")
        logger.info(f" max value [D]  :: {self.max}")
        logger.info(" --------- ")

    def get_histgram(self):
        """
        Calculates and saves the histogram data of the dipole magnitudes.

        This method computes the magnitude of the dipole moments from the input
        data, generates a histogram, and saves the histogram data to a CSV file.
        The histogram is generated with a fixed number of bins (1000), which should be modified.

        Returns
        -------
        pandas.DataFrame
            A DataFrame containing the dipole values and their corresponding densities.

        Examples
        --------
        >>> hist_plotter = Plot_histgram("dipole.txt", max=5.0)
        >>> hist_data = hist_plotter.get_histgram()
        >>> print(hist_data.head())
               dipole   density
        0  0.0025  0.0001
        1  0.0075  0.0002
        2  0.0125  0.0003
        3  0.0175  0.0004
        4  0.0225  0.0005
        """

        # 先にデータの数と値域から最適なヒストグラム構成を考える
        # TODO :: bins = 1000で固定しているので修正
        _length = len(self.data)

        # 最大値を計算する
        plot_data = np.linalg.norm(self.data[:, 2:].reshape(-1, 3), axis=1)
        _max_val = np.max(plot_data)
        # 最大値が4以下なら5で固定する
        if self.max != None:
            _hist_max_val = float(self.max)
        elif _max_val < 4:
            _hist_max_val = 5
        else:
            _hist_max_val = _max_val + 2

        # https://qiita.com/nkay/items/56bda7143981e3d5303f
        df = pd.DataFrame()
        hist = np.histogram(
            plot_data, bins=1000, range=[0, _hist_max_val], density=True
        )
        df["dipole"] = (hist[1][1:] + hist[1][:-1]) / 2
        df["density"] = hist[0]
        df.to_csv(self._filename + "_hist.txt")
        return df

    def plot_dipole_histgram(self):
        """make histgram & plot histgram

        Returns:
            _type_: _description_
        """
        logger.info(" ---------- ")
        logger.info(" dipole histgram plot ")
        logger.info(" ---------- ")

        # 最大値を計算する
        plot_data = np.linalg.norm(self.data[:, 2:].reshape(-1, 3), axis=1)
        _max_val = np.max(plot_data)
        # 最大値が4以下なら5で固定する
        if self.max != None:
            _hist_max_val = float(self.max)
        elif _max_val < 4:
            _hist_max_val = 5
        else:
            _hist_max_val = _max_val + 2

        plot_data = np.linalg.norm(self.data[:, 2:].reshape(-1, 3), axis=1)
        # figure, axesオブジェクトを作成
        fig, ax = plt.subplots(figsize=(8, 5), tight_layout=True)
        ax.hist(plot_data, bins=1000, range=[0, _hist_max_val], density=True)  # 描画

        # 各要素で設定したい文字列の取得
        xlabel = "Dipole [D]"  # "Time $\mathrm{ps}$"
        ylabel = "Density"

        # 各要素の設定を行うsetコマンド
        ax.set_xlabel(xlabel, fontsize=22)
        ax.set_ylabel(ylabel, fontsize=22)
        ax.tick_params(axis="x", labelsize=15)
        ax.tick_params(axis="y", labelsize=15)
        ax.legend(loc="upper right", fontsize=15)
        fig.savefig(self._filename + "_dipolehist.pdf")
        fig.delaxes(ax)
        return 0


# --------------------------------
# 以下CPextract.pyからロードする関数たち
# --------------------------------


def command_diel_histgram(args):
    EVP = PlotDipoleHistgram(args.Filename, args.max)
    EVP.get_histgram()
    EVP.plot_dipole_histgram()
    return 0
