#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""cpextract_diel.py
CPextract.py diel subcommand for processing dipole.txt files generated by dieltools

- histgram :: Plot histgram of molecule dipole/bond dipole
"""


#
# simple code to extract data from CP.x outputs
# define sub command of CPextract.py
#

import numpy as np
import matplotlib.pyplot as plt
from mlwc.fourier.acf_fourier import (
    dielec,
    calc_total_mol_acf_self,
    calc_total_mol_acf_cross
)
from mlwc.fourier.dipole_core import diel_function
from mlwc.include.mlwc_logger import setup_library_logger
logger = setup_library_logger("MLWC."+__name__)


class Plot_totaldipole:
    """plot time vs dipole figure for total_dipole

    Returns:
        _type_: _description_
    """

    def __init__(self, dipole_filename):
        self._filename = dipole_filename
        import os
        if not os.path.isfile(self._filename):
            logger.error(" ERROR (Plot_totaldipole) :: " +
                         str(self._filename)+" does not exist !!")
            logger.error(" ")
            return 1
        logger.info(" ============================ ")
        logger.info(f" filename  :: {self._filename}")
        # load txt in numpy ndarray
        self.data = np.loadtxt(self._filename, comments='#')
        logger.info(f" number of data :: {np.shape(self.data)}")
        self.__get_timestep()
        logger.info(f" timestep [fs] :: {self.timestep}")
        self.__get_temperature()
        logger.info(f" temperature [K] :: {self.temperature}")
        self.__get_unitcell()
        logger.info(f" unitcell [Ang] :: {self.unitcell}")
        logger.info(" ============================ ")

    def __get_timestep(self) -> int:
        """extract timestep [fs] from total_dipole.txt
        """
        with open(self._filename) as f:
            line = f.readline()
            while line:
                line = f.readline()
                if line.startswith("#TIMESTEP"):
                    time = float(line.split(" ")[1])
                    break
        self.timestep = time
        return 0

    def __get_unitcell(self):
        """extract unitcell from total_dipole.txt
        """
        with open(self._filename) as f:
            line = f.readline()
            while line:
                line = f.readline()
                if line.startswith("#UNITCELL"):
                    unitcell = line.strip("\n").strip().split(" ")[1:]
                    break
        self.unitcell = np.array([float(i) for i in unitcell]).reshape([3, 3])
        return 0

    def __get_temperature(self):
        """extract unitcell from total_dipole.txt
        """
        with open(self._filename) as f:
            line = f.readline()
            while line:
                line = f.readline()
                if line.startswith("#TEMPERATURE"):
                    temp = float(line.split(" ")[1])
                    break
        self.temperature = temp
        return 0

    def calc_dielectric_spectrum(self, eps_n2: float, start: int, end: int, step: int, window: str = "hann", if_fft: bool = True):
        """total dipole.txtから全スペクトルを計算する

        Args:
            eps_n2 (float): _description_
            start (int): _description_
            end (int): _description_
            step (int): _description_

        Returns:
            _type_: _description_
        """
        logger.info(" ==================== ")
        logger.info(f"  start index :: {start}")
        logger.info(f"  end   index :: {end}")
        logger.info(f" moving average step :: {step}")
        logger.info(" ==================== ")
        process = dielec(self.unitcell, self.temperature, self.timestep)
        if end == -1:
            calc_data = self.data[start:, 1:]  # dipoleのみを抽出
        else:
            calc_data = self.data[start:end, 1:]  # dipoleのみを抽出
        logger.info(" ====================== ")
        logger.info(f"  len(data)          :: {len(calc_data)}")
        logger.info(
            f"  total MD time [ps] :: {len(calc_data)*self.timestep/1000}")
        logger.info(" ====================== ")
        if (start >= end) and (end != -1):
            raise ValueError("end must be larger than start")

        # replace abnormally large dipole (10*average dipole) with previous values
        ave_dipole = np.mean(np.linalg.norm(calc_data, axis=1))
        calc_data = np.where(np.abs(calc_data) > 10*ave_dipole,
                             0, calc_data)  # 双極子のズレが大きい場合は0で置き換え
        # here, we do not include moving-average
        rfreq, ffteps1, ffteps2 = process.calc_fourier(
            calc_data, eps_n2, window, if_fft)  # calc dielectric function
        # here, we introduce moving-average for both dielectric-function and refractive-index
        diel = diel_function(rfreq, ffteps1, ffteps2, step)
        diel.diel_df.to_csv(self._filename+"_diel.csv")
        diel.refractive_df.to_csv(self._filename+"_refractive.csv")
        return 0

    def calc_dielectric_derivative_spectrum(self, start: int, end: int, step: int):
        """微分スペクトルから計算する．公式はzhang2020Deepを利用

        Args:
            eps_n2 (float): _description_
            start (int): _description_
            end (int): _description_
            step (int): _description_
        """
        from fourier.acf_fourier import dielec
        from fourier.dipole_core import diel_function
        process = dielec(self.unitcell, self.temperature, self.timestep)
        if end == -1:
            calc_data = self.data[start:, 1:]
        else:
            calc_data = self.data[start:end, 1:]
        # calculate alphan
        rfreq, alphan = process.calc_derivative_spectrum(
            calc_data, window="hann")
        import pandas as pd
        df = pd.DataFrame()
        df["freq_thz"] = rfreq
        df["freq_kayser"] = rfreq*33.3
        window = np.ones(step)/step
        df["alphan"] = np.convolve(alphan, window, mode="same")
        df.to_csv(self._filename+"_alphan.csv")
        return 0

    def plot_total_dipole(self):
        """make histgram&plot histgram

        Returns:
            _type_: _description_
        """
        logger.info(" ---------- ")
        logger.info(" dipole histgram plot ")
        logger.info(" ---------- ")
        # figure, axesオブジェクトを作成
        fig, ax = plt.subplots(figsize=(8, 5), tight_layout=True)
        ax.plot(self.data[:, 0]*self.timestep/1000,
                self.data[:, 1], label="x")     # 描画
        ax.plot(self.data[:, 0]*self.timestep/1000,
                self.data[:, 2], label="y")     # 描画
        ax.plot(self.data[:, 0]*self.timestep/1000,
                self.data[:, 3], label="z")     # 描画

        # 各要素で設定したい文字列の取得
        xticklabels = ax.get_xticklabels()
        yticklabels = ax.get_yticklabels()
        xlabel = "Time [ps]"  # "Time $\mathrm{ps}$"
        ylabel = "Dipole [D]"

        # 各要素の設定を行うsetコマンド
        ax.set_xlabel(xlabel, fontsize=22)
        ax.set_ylabel(ylabel, fontsize=22)

        # https://www.delftstack.com/ja/howto/matplotlib/how-to-set-tick-labels-font-size-in-matplotlib/#ax.tick_paramsaxis-xlabelsize-%25E3%2581%25A7%25E7%259B%25AE%25E7%259B%259B%25E3%2582%258A%25E3%2583%25A9%25E3%2583%2599%25E3%2583%25AB%25E3%2581%25AE%25E3%2583%2595%25E3%2582%25A9%25E3%2583%25B3%25E3%2583%2588%25E3%2582%25B5%25E3%2582%25A4%25E3%2582%25BA%25E3%2582%2592%25E8%25A8%25AD%25E5%25AE%259A%25E3%2581%2599%25E3%2582%258B
        ax.tick_params(axis='x', labelsize=15)
        ax.tick_params(axis='y', labelsize=15)

        ax.legend(loc="upper right", fontsize=15)

        # pyplot.savefig("eps_real2.pdf",transparent=True)
        # plt.show()
        fig.savefig(self._filename+"_time_dipole.pdf")
        fig.delaxes(ax)
        return 0


class Plot_moleculedipole(Plot_totaldipole):
    """plot time vs dipole figure for total_dipole

    Returns:
        _type_: _description_
    """

    def __init__(self, dipole_filename):
        # 継承元から初期化
        super().__init__(dipole_filename)
        self.__get_num_mol()
        logger.info(" --------- ")
        logger.info(f" number of mol :: {self.__NUM_MOL}")
        logger.info(" --------- ")
        # データ形状を変更[frame,mol_id,3dvector]
        self.data = self.data[:, 2:].reshape(-1, self.__NUM_MOL, 3)

    def __get_num_mol(self):
        """extract num_mol from molecule_dipole.txt
        """
        # 1行目の最大値が分子数
        self.__NUM_MOL = int(np.max(self.data[:, 1]))+1
        return 0

    def calc_dielectric_spectrum(self, eps_n2: float, start: int, end: int, step: int):
        logger.info(" ==================== ")
        logger.info(f"  start index :: {start}")
        logger.info(f"  end   index :: {end}")
        logger.info(f" moving average step :: {step}")
        logger.info(" ==================== ")
        process = dielec(self.unitcell, self.temperature, self.timestep)
        if end == -1:
            calc_data = self.data[start:, :, :]
        else:
            calc_data = self.data[start:end, :, :]
        logger.info(" ====================== ")
        logger.info(f"  len(data)    :: {len(calc_data)}")
        logger.info(" ====================== ")
        # self term ACF
        self_data = calc_total_mol_acf_self(calc_data, engine="tsa")
        rfreq_self, ffteps1_self, ffteps2_self = process.calc_fourier_only_with_window(
            self_data, eps_n2, window="hann")
        # here, we introduce moving-average for both dielectric-function and refractive-index
        diel_self = diel_function(rfreq_self, ffteps1_self, ffteps2_self, step)
        diel_self.diel_df.to_csv(self._filename+"_self_diel.csv")
        diel_self.refractive_df.to_csv(self._filename+"_self_refractive.csv")
        logger.info(" finish self terms")
        # cross term ACF
        cross_data = calc_total_mol_acf_cross(calc_data, engine="tsa")
        logger.info(" finish cross terms")
        # rfreq_self = rfreq_cross
        rfreq_cross, ffteps1_cross, ffteps2_cross = process.calc_fourier_only_with_window(
            cross_data, eps_n2, window="hann")
        rfreq_total, ffteps1_total, ffteps2_total = process.calc_fourier_only_with_window(
            self_data+cross_data, eps_n2, window="hann")
        # cross
        diel_cross = diel_function(
            rfreq_cross, ffteps1_cross, ffteps2_cross, step)
        diel_cross.diel_df.to_csv(self._filename+"_cross_diel.csv")
        diel_cross.refractive_df.to_csv(self._filename+"_cross_refractive.csv")
        # total
        diel_total = diel_function(
            rfreq_total, ffteps1_total, ffteps2_total, step)
        diel_total.diel_df.to_csv(self._filename+"_total_diel.csv")
        diel_total.refractive_df.to_csv(self._filename+"_total_refractive.csv")
        return 0


# --------------------------------
# load from CPextract.py
# --------------------------------

def command_diel_total(args):
    EVP = Plot_totaldipole(args.Filename)
    EVP.plot_total_dipole()
    return 0
