#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""cpextract_diel.py
CPextract.py diel subcommand for processing dipole.txt files generated by dieltools

- histgram :: Plot histgram of molecule dipole/bond dipole
"""


import datetime

import __version__
from mlwc.fourier.dipole_core import diel_function
from mlwc.fourier.totaldipole.totaldipole_io import read_file
from mlwc.include.file_io import to_csv_with_comment
from mlwc.include.mlwc_logger import setup_library_logger

logger = setup_library_logger("MLWC." + __name__)


# --------------------------------
# load from CPextract.py
# --------------------------------


def command_diel_spectra(args):

    # moving average:: https://chaos-kiyono.hatenablog.com/entry/2022/07/25/212843
    # https://qiita.com/FallnJumper/items/e0afa1fb05ea448caae1
    if args.fft == "True":
        if_fft = True
    elif args.fft == "False":
        if_fft = False
    else:
        raise ValueError("fft should be True or False")
    # dielectric function
    total_dipole = read_file(args.Filename, int(args.start), int(args.end))
    df_refractive = total_dipole.calculate_refractiveindex(
        eps_inf=float(args.eps), method_dipole="direct", window_type=args.window
    )
    # save to a file
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    comment = f"""
    # File created on: {current_time}\n
    # File generated by CPextract.py diel resample version {__version__.__version__}.\n
    # Parameters: filename={args.Filename}\n
    # Parameters: eps_inf ={float(args.eps)}\n
    # Parameters: window  ={args.window}\n
    # Data below:\n
    """
    to_csv_with_comment(df_refractive, comment, args.Filename + "_refractive.csv")

    # TODO :: apply moving average to df_refractive
    diel = diel_function(
        df_refractive["freq_thz"],
        df_refractive["diel_real"],
        df_refractive["diel_imag"],
        int(args.step),
    )
    diel.diel_df.to_csv(args.Filename + "_diel_test.csv")
    # diel.refractive_df.to_csv(args.Filename+"_refractive_test.csv")
    # calculate alphan through derivative formula
    df_alphan = total_dipole.calculate_absorption(method_dipole="derivative")
    df_alphan.to_csv(args.Filename + "_alphan.csv", index=False)
    return 0
