#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""CPextract.py diel spectra"""


import argparse
import datetime

import __version__
from mlwc.fourier.totaldipole.totaldipole_io import read_file
from mlwc.include.file_io import to_csv_with_comment
from mlwc.include.mlwc_logger import setup_library_logger

logger = setup_library_logger("MLWC." + __name__)


def command_diel_spectra(args: argparse.Namespace):
    """Entry point of CPextract.py diel spectra"""
    # dielectric function
    total_dipole = read_file(args.Filename, int(args.start), int(args.end))
    df_refractive = total_dipole.calculate_refractiveindex(
        eps_inf=float(args.eps), method_dipole="direct", window_type=args.window
    )
    # save to a file
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    comment = f"""
    # File created on: {current_time}\n
    # File generated by CPextract.py diel resample version {__version__.__version__}.\n
    # Parameters: filename={args.Filename}\n
    # Parameters: start   ={args.start}\n
    # Parameters: end     ={args.end}\n
    # Parameters: eps_inf ={float(args.eps)}\n
    # Parameters: window  ={args.window}\n
    # Data below:\n
    """
    to_csv_with_comment(df_refractive, comment, args.Filename + "_refractive.csv")

    # calculate alphan through derivative formula
    df_alphan = total_dipole.calculate_absorption(method_dipole="derivative")
    to_csv_with_comment(df_alphan, comment, args.Filename + "_alphan.csv")
    return 0
