import os

import __version__
import ase
import ase.io

from mlwc.analysis_trajectory.msd import calculate_msd
from mlwc.include.file_io import to_csv_with_comment
from mlwc.include.mlwc_logger import setup_cmdline_logger

logger = setup_cmdline_logger(__name__)


def command_cpmd_msd(args) -> int:  # mean square displacement
    if not os.path.isfile(args.Filename):
        raise FileNotFoundError(
            " ERROR :: " + str(args.Filename) + " does not exist !!"
        )

    initial_step = int(args.initial_step)
    timestep = float(args.timestep)
    if initial_step < 0:
        raise ValueError("ERROR: initial_step must be larger than 0")

    # read xyz
    logger.info(" READING TRAJECTORY... This may take a while, be patient.")
    traj = ase.io.read(args.Filename, index=":")

    df, diffusion_coefficient = calculate_msd(traj, initial_step, timestep)
    logger.info(f" diffusion_coefficient = {diffusion_coefficient}[m^2/s]")
    comment: str = f"""
        # File generated by CPextract.py cpmd msd version {__version__.__version__}.
        # Parameters: trajectory filename={args.Filename}
        # Parameters: initial_step={initial_step}, timestep={timestep}
        # Data below:\n
        """
    to_csv_with_comment(df, comment, args.Filename + "_msd.csv")
    return 0
