#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""cpextract_diel.py
CPextract.py diel subcommand for processing dipole.txt files generated by dieltools

- histgram :: Plot histgram of molecule dipole/bond dipole
"""


#
# simple code to extract data from CP.x outputs
# define sub command of CPextract.py
#

import sys
import numpy as np
import pandas as pd
import argparse
import matplotlib.pyplot as plt
import dataio.read_core
import dataio.cpx.read_traj
import ase.units
from fourier.acf_fourier import dielec
from fourier.acf_fourier import calc_total_mol_acf_self
from fourier.acf_fourier import calc_total_mol_acf_cross
from fourier.dipole_core import diel_function
from fourier.totaldipole.totaldipole import totaldipole
from fourier.totaldipole.totaldipole_io import read_file

from include.mlwc_logger import setup_library_logger
logger = setup_library_logger("MLWC."+__name__)


class Plot_totaldipole:
    """plot time vs dipole figure for total_dipole

    Returns:
        _type_: _description_
    """

    def __init__(self, dipole_filename):
        self._filename = dipole_filename
        import os
        if not os.path.isfile(self._filename):
            logger.error(" ERROR (Plot_totaldipole) :: " +
                         str(self._filename)+" does not exist !!")
            logger.error(" ")
            return 1
        logger.info(" ============================ ")
        logger.info(f" filename  :: {self._filename}")
        # load txt in numpy ndarray
        self.data = np.loadtxt(self._filename, comments='#')
        logger.info(f" number of data :: {np.shape(self.data)}")
        self.__get_timestep()
        logger.info(f" timestep [fs] :: {self.timestep}")
        self.__get_temperature()
        logger.info(f" temperature [K] :: {self.temperature}")
        self.__get_unitcell()
        logger.info(f" unitcell [Ang] :: {self.unitcell}")
        logger.info(" ============================ ")

    def __get_timestep(self) -> int:
        """extract timestep [fs] from total_dipole.txt
        """
        with open(self._filename) as f:
            line = f.readline()
            while line:
                line = f.readline()
                if line.startswith("#TIMESTEP"):
                    time = float(line.split(" ")[1])
                    break
        self.timestep = time
        return 0

    def __get_unitcell(self):
        """extract unitcell from total_dipole.txt
        """
        with open(self._filename) as f:
            line = f.readline()
            while line:
                line = f.readline()
                if line.startswith("#UNITCELL"):
                    unitcell = line.strip("\n").strip().split(" ")[1:]
                    break
        self.unitcell = np.array([float(i) for i in unitcell]).reshape([3, 3])
        return 0

    def __get_temperature(self):
        """extract unitcell from total_dipole.txt
        """
        with open(self._filename) as f:
            line = f.readline()
            while line:
                line = f.readline()
                if line.startswith("#TEMPERATURE"):
                    temp = float(line.split(" ")[1])
                    break
        self.temperature = temp
        return 0

    def calc_dielectric_spectrum(self, eps_n2: float, start: int, end: int, step: int, window: str = "hann", if_fft: bool = True):
        """total dipole.txtから全スペクトルを計算する

        Args:
            eps_n2 (float): _description_
            start (int): _description_
            end (int): _description_
            step (int): _description_

        Returns:
            _type_: _description_
        """
        logger.info(" ==================== ")
        logger.info(f"  start index :: {start}")
        logger.info(f"  end   index :: {end}")
        logger.info(f" moving average step :: {step}")
        logger.info(" ==================== ")
        process = dielec(self.unitcell, self.temperature, self.timestep)
        if end == -1:
            calc_data = self.data[start:, 1:]  # dipoleのみを抽出
        else:
            calc_data = self.data[start:end, 1:]  # dipoleのみを抽出
        logger.info(" ====================== ")
        logger.info(f"  len(data)          :: {len(calc_data)}")
        logger.info(
            f"  total MD time [ps] :: {len(calc_data)*self.timestep/1000}")
        logger.info(" ====================== ")
        if (start >= end) and (end != -1):
            raise ValueError("end must be larger than start")

        # replace abnormally large dipole (10*average dipole) with previous values
        ave_dipole = np.mean(np.linalg.norm(calc_data, axis=1))
        calc_data = np.where(np.abs(calc_data) > 10*ave_dipole,
                             0, calc_data)  # 双極子のズレが大きい場合は0で置き換え
        total_dipole = totaldipole().set_params(
            calc_data, self.unitcell, self.timestep, self.temperature)
        dielfunction = total_dipole.calculate_dielfunction(
            eps_inf=eps_n2, method_dipole="direct", window_type=window)
        rfreq = dielfunction["freq_thz"]
        ffteps1 = dielfunction["diel_real"]
        ffteps2 = dielfunction["diel_imag"]

        # # here, we do not include moving-average
        # rfreq, ffteps1, ffteps2 = process.calc_fourier(
        #     calc_data, eps_n2, window, if_fft)  # calc dielectric function

        # here, we introduce moving-average for both dielectric-function and refractive-index
        diel = diel_function(rfreq, ffteps1, ffteps2, step)
        diel.diel_df.to_csv(self._filename+"_diel.csv")
        diel.refractive_df.to_csv(self._filename+"_refractive.csv")
        return 0

    def calc_dielectric_derivative_spectrum(self, start: int, end: int, step: int):
        """微分スペクトルから計算する．公式はzhang2020Deepを利用

        Args:
            eps_n2 (float): _description_
            start (int): _description_
            end (int): _description_
            step (int): _description_
        """
        from fourier.acf_fourier import dielec
        from fourier.dipole_core import diel_function
        process = dielec(self.unitcell, self.temperature, self.timestep)
        if end == -1:
            calc_data = self.data[start:, 1:]
        else:
            calc_data = self.data[start:end, 1:]
        # calculate alphan
        rfreq, alphan = process.calc_derivative_spectrum(
            calc_data, window="hann")
        import pandas as pd
        df = pd.DataFrame()
        df["freq_thz"] = rfreq
        df["freq_kayser"] = rfreq*33.3
        window = np.ones(step)/step
        df["alphan"] = np.convolve(alphan, window, mode="same")
        df.to_csv(self._filename+"_alphan.csv")
        return 0

# --------------------------------
# 以下CPextract.pyからロードする関数たち
# --------------------------------


def command_diel_spectra(args):
    EVP = Plot_totaldipole(args.Filename)

    EVP.calc_dielectric_spectrum(float(args.eps), int(args.start), int(
        args.end), int(args.step), args.window, if_fft)  # epsを受け取ってfloat変換
    EVP.calc_dielectric_derivative_spectrum(
        int(args.start), int(args.end), int(args.step))  # 微分公式のテスト

    # moving average:: https://chaos-kiyono.hatenablog.com/entry/2022/07/25/212843
    # https://qiita.com/FallnJumper/items/e0afa1fb05ea448caae1
    if args.fft == "True":
        if_fft = True
    elif args.fft == "False":
        if_fft = False
    else:
        raise ValueError("fft should be True or False")
    # dielectric function
    total_dipole = read_file(args.Filename, args.start, args.end)
    diel_function = total_dipole.calculate_dielfunction(
        eps_inf=args.eps, method_dipole="direct")

    return 0
